config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :islands, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [] do
      member do
        get '/acceptbooking', to: "bookings#accept_booking", as: "accept_booking"
        get '/refusebooking', to: "bookings#refuse_booking", as: "refuse_booking"
      end
    end
  resources :bookings, only: :show
  get '/dashboard', to: "pages#dashboard", as: "dashboard"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :island
  belongs_to :user
end

app/models/island.rb
class Island < ApplicationRecord
  belongs_to :user
  has_many :bookings
  mount_uploader :photo, PhotoUploader

  geocoded_by :name
  after_validation :geocode, if: :will_save_change_to_location?

  validates :name, presence: true, allow_blank: false
  validates :description, presence: true, allow_blank: false
  validates :price, presence: true, numericality: { only_integer: true }, allow_blank: false
  validates :photo, presence: true
  validates :location, presence: true, allow_blank: false
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :islands
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @island = Island.find(params[:island_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @island = Island.find(params[:island_id])
    @booking.user = current_user
    @booking.island = @island

    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def accept_booking
    @booking = Booking.find(params[:id])
    @booking.status = 'accepted'
    @booking.save
    redirect_to dashboard_path
  end

  def refuse_booking
    @booking = Booking.find(params[:id])
    @booking.status = 'rejected'
    @booking.destroy
    redirect_to dashboard_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/islands_controller.rb
class IslandsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :index]

  def index
    if params[:query].present?
      sql_query = "location ILIKE :query OR description ILIKE :query"
      @islands = Island.where(sql_query, query: "%#{params[:query]}")
    else
    @islands = Island.geocoded # returns islands with coordinates
    end

    @markers = @islands.map do |island|
      {
        lat: island.latitude,
        lng: island.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { islands: island }),
        image_url: helpers.asset_url('https://avatars2.githubusercontent.com/u/5470001?s=200&v=4')
      }
    end
  end

  def show
    @island = Island.find(params[:id])
  end

  def new
    @island = Island.new
  end

  def create
    @island = Island.new(island_params)
    @island.user = current_user
    if @island.save
      redirect_to island_path(@island)
    else
      render :new
    end
  end

  private

  def island_params
    params.require(:island).permit(:name, :description, :price, :photo, :location)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<%= image_tag "islandhuts.jpg", class:"form-background-image fixed-right"%>
<div class="form-content">
  <div class="container">
    <div class="form">
      <h1>Booking</h1>
        <%= simple_form_for [@island, @booking] do |f| %>
        <%= f.input :start_date, placeholder: "Start date", label: false %>
        <%= f.input :end_date, placeholder: "End date", label: false %>
        <%= f.button :submit, class:"btn btn-atoll w-100", value:"Request booking" %>
        <% end %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container mt-3">
  <div class="card-trip-large">
    <div class="d-flex justify-content-between mt-3 mb-3">
      <h2>Booking Confirmation for: <%= @booking.island.name %></h2>
      <div class="card-trip-dates d-flex justify-content-around">
        <div>
          <h4>Check in</h4>
          <p><%= @booking.start_date %></p>
        </div>
        <div>
          <h4>Check out</h4>
          <p><%= @booking.end_date %></p>
        </div>
      </div>
    </div>

    <%= cl_image_tag @booking.island.photo %>

    <div class="price-description mt-3">
      <div>
        <h4><strong>$<%= @booking.island.price %></strong></h4>
        <p>per night</p>
      </div>

      <div>
        <%= link_to "Book Another Island", islands_path, class:"btn btn-book mt-3" %>
      </div>
    </div>
  </div>
</div>

app/views/islands/_info_window.html.erb
<div class="map-box">
<%= link_to islands.name, island_path(islands) %>
</div>

app/views/islands/index.html.erb
<div class="main-container">
  <div class="container-card-title">
    <div class="cards-title">
      <% if @islands.count > 1 %>
      <h1><%= @islands.count %> Islands found: <strong><%= params[:query].capitalize %></strong></h1>
      <% else %>
      <h1><%= @islands.count %> Island found: <strong><%= params[:query].capitalize %></strong></h1>
      <% end %>
    </div>
    <div class="cards">
      <% @islands.each do |island| %>
        <%= link_to island_path(island) do %>
          <div class="card-trip">
            <%= cl_image_tag island.photo %>
            <div class="card-trip-infos">
              <div>
                <h2><%= island.name %></h2>
                <p><%= island.location %></p>
              </div>
              <h2 class="card-trip-pricing">$<%= island.price %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div
    id="map"
    style="width: 100%"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/islands/new.html.erb
<div class="form-content">
  <div class="container">
    <div class="form">
      <h1>Host your island</h1>
      <%= simple_form_for (@island) do |f| %>
        <%= f.input :name, placeholder: "Name", label: false %>
        <%= f.input :location, placeholder: "Location", label: false %>
        <%= f.input :description, placeholder: "Description", label: false, :as => :text, input_html: { :style=> 'width: 100%;', :rows => 4} %>
        <%= f.input :price, placeholder: "Price (per night)", label: false %>
        <%= f.input :photo, label: false%>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.button :submit, class:"btn btn-atoll w-100", value:"Host island" %>
      <% end %>
    </div>
  </div>
</div>

<%= image_tag "islandhuts.jpg", class:"form-background-image fixed-right"%>

app/views/islands/show.html.erb
<div class="container mt-5">
  <div class="card-trip-large">
    <div class="d-flex justify-content-between mt-3 mb-3">
      <div>
        <h2><%= @island.name %></h2>
        <p><%= @island.location %></p>
      </div>
      <div>
        <%= link_to "Book Now", new_island_booking_path(@island), class:"btn btn-book mt-3" %>
      </div>
    </div>
    <%= cl_image_tag @island.photo %>
    <div class="price-description mt-3">
      <div class="trip-description">
        <h3 class="mb-1">Description</h3>
        <p id="description-text"><%= @island.description %></p>
      </div>
      <div>
        <h4><strong>$<%= @island.price %></strong></h4>
        <p>per night</p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Atoll</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body style="display: block;">
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container-dashboard">
  <div class="flexbox">
    <div class="col-10 offset-1 col-md-6">
      <div class="hosting">
      <h1>My bookings</h1>
        <% current_user.bookings.each do |booking| %>
          <p class="hosting-pending"><%= booking.status.capitalize %></p>
          <%= link_to island_path(booking.island) do %>
            <div class="card-trip">
              <%= cl_image_tag booking.island.photo%>
              <div class="card-trip-infos">
                <div>
                  <h2><%= booking.island.name %></h2>
                  <p><%= booking.island.location %></p>
                </div>
                <h2 class="card-trip-pricing">$<%= booking.island.price %></h2>
                <!-- <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" /> -->
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="col-10 offset-1 col-md-6">
      <div class="hosting">
        <h1>My hostings</h1>
        <% current_user.islands.each do |island| %>
          <% island.bookings.each do |booking| %>
            <div class="hosting-details-buttons">
              <div class="hosting-details">
                <p>Your island is booked by: <strong><%= booking.user.first_name.capitalize %></strong></p>
                <p>From: <%= booking.start_date %> until <%= booking.end_date %></p>
              </div>
              <div class="hosting-buttons">
                <%= link_to "Accept", accept_booking_booking_path(booking), class:"btn btn-book mt-3" %>
                <%= link_to "Decline", refuse_booking_booking_path(booking), class:"btn btn-book mt-3" %>
              </div>
            </div>
            <div class="hosting-card">
              <%= link_to island_path(booking.island) do %>
                <div class="card-trip">
                  <%= cl_image_tag booking.island.photo%>
                  <div class="card-trip-infos">
                    <div>
                      <h2><%= booking.island.name %></h2>
                      <p><%= booking.island.location %></p>
                    </div>
                    <h2 class="card-trip-pricing">$<%= booking.island.price %></h2>
                    <!-- <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" /> -->
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>

<head>
<meta charset="UTF-8">
<title>Atoll homepage</title>
</head>

<body>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url(assets/seabeach.jpg)">
    <div class="container">
      <h1>Find your <strong>Paradise</strong></h1>
      <h2>Discover and book island getaways with no hassle atoll</h2>
      <form novalidate="novalidate" class="simple_form search" action="/islands" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" />
        <div class="search-form-control form-group">
          <input class="form-control string required" type="text" name="query" id="search_query" placeholder="Location" />
          <button name="button" type="submit" class="btn btn-flat">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </form>
    </div>
  </div>
</body>

</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <h2 class="logo">Atoll</h2>
  <% end %>
  <% unless current_page?("/") %>
    <div class="container-nav">
      <form novalidate="novalidate" class="simple_form search search-nav" action="/islands" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" />
        <div class="search-form-control form-group">
          <input class="form-control string required" type="text" name="query" id="search_query_nav" placeholder="Location" />
          <button name="button" type="submit" class="btn btn-flat">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </form>
    </div>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item-button">
        <%= link_to "Host An Island", new_island_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item-button">
          <%= link_to "Log out", destroy_user_session_path, class: "nav-link", method: :delete %>
        </li>
        <li class="nav-item-button">
          <%= link_to dashboard_path, class: "nav-link" do%>
            <%= image_tag "logo.png", class: "avatar dropdown-toggle" %>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item-button">
          <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>